services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: backend
    ports:
      - 5000:5000
    environment:
      - OLLAMA_SERVICE_NAME=ollama:11434
    depends_on:
      - ollama
    networks:
      - backend-frontend
      - backend-ollama

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.chiselled.full
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - BACKEND_SERVICE_NAME=backend:5000
    depends_on:
      - backend
    networks:
      - backend-frontend


networks:
  backend-frontend:
