services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: backend
    ports:
      - 5000:5000
    environment:
      - JWT_SECRET=matuvugu
    networks:
      - backend-frontend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - BACKEND_SERVICE_NAME=backend:5000
    depends_on:
      - backend
    networks:
      - backend-frontend


networks:
  backend-frontend:
