services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - backend-frontend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - backend-frontend


networks:
  backend-frontend:
